server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.222.140:3306/tensquare_recruit?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
